// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPDF(arg1:Array<main.PageSelection>,arg2:string):Promise<main.ExportResult>;

export function OpenPDFs():Promise<Array<main.PDFDocument>>;
